## Homework copying

To identify questions that were copied from homework assignments, all available homework assignments were saved in a single Word document. The document is treated as one continuous reference text, and each question is compared against this text using fuzzy partial-ratio matching.

The matching procedure was first tested on individual questions for which the classification was known in advance.

In [1]:
import pandas as pd

df = pd.read_excel('databases/chat_database_time.xlsx')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 46 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   chat_id              990 non-null    int64
 1   question_id          990 non-null    int64
 2   question             990 non-null    object
 3   answer               990 non-null    object
 4   q_time               990 non-null    datetime64[ns]
 5   a_time               990 non-null    object
 6   id                   990 non-null    object
 7   T1                   990 non-null    float64
 8   T2                   990 non-null    float64
 9   T3                   990 non-null    float64
 10  T4                   990 non-null    float64
 11  T1234                990 non-null    float64
 12  question_length      990 non-null    int64
 13  answer_length        990 non-null    int64
 14  question_count       990 non-null    int64
 15  chat_count           990 non-null    int64
 16  relevance            990 non-null    int64
 17  avg_question_length  990 non-null    float64
 18  avg_answer_length    990 non-null    float64
 19  row_id               990 non-null    int64
 20  q_date               990 non-null    datetime64[ns]
 21  active_days          990 non-null    int64
 22  profile              990 non-null    object
 23  relevance_rate       990 non-null    float64
 24  non_rewarded         990 non-null    int64
 25  non_rewarded_count   990 non-null    int64
 26  total_questions      990 non-null    int64
 27  non_rewarded_share   990 non-null    float64
 28  rewarded_count       990 non-null    int64
 29  rewarded_share       990 non-null    float64
 30  active_days_rew      990 non-null    int64
 31  active_days_post     990 non-null    int64
 32  exam_panic           990 non-null    int64
 33  exam_panic_rate      990 non-null    float64
 34  q_len_rew            866 non-null    float64
 35  q_len_post           124 non-null    float64
 36  a_len_rew            866 non-null    float64
 37  a_len_post           124 non-null    float64
 38  avg_q_len_rew        990 non-null    float64
 39  avg_q_len_post       683 non-null    float64
 40  avg_a_len_rew        990 non-null    float64
 41  avg_a_len_post       683 non-null    float64
 42  rel_rew              866 non-null    float64
 43  rel_post             124 non-null    float64
 44  avg_rel_rew          990 non-null    float64
 45  avg_rel_post         683 non-null    float64
dtypes: datetime64[ns](2), float64(23), int64(16), object(5)
memory usage: 355.9+ KB

In [3]:
from docx import Document

doc = Document('homeworks/homeworks.docx')

# Extract all homework assignments as a single text string
texts = "\n".join([p.text for p in doc.paragraphs])

print(type(texts))
print(len(texts))
print(texts)

<class 'str'>
79484
"A Z változó eloszlása 6 várható érték¶ és 10 szórású normális eloszlás. Mekkora valószín¶séggel esik Z
értéke az alábbi halmazokba?"
"Mintavételes vizsgálattal akarják megmérni néhány városban a rabszolgatartás visszaállítását támogatók arányát. Az alábbiakban a várható érték és a standard hiba megadását kérjük!
Tegyük fel, hogy E városban 20% a támogatók viszont 80% az ellenz®k aránya. Egy, az E városból vett
 n = 120 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 550 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 1100 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 10000 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
Tegyük fel, hogy F városban 60% a támogatók viszont csak 40% az ellenz®ké. Egy, az F városból vett
 n = 120 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 550 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 1100 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra.
 n = 10000 f®s mintánál a mintában a támogatók aránya % körül lesz, attól ± kb. %-ra"
Szabályos kockával egymás után kétszer dobunk. Mi a valószín¶sége annak, hogy 3-mal osztható a két dobás szorzata, ha az els® kockával párost dobtunk?
Egy dobozban dobozban 4 piros, 5 kék és 3 zöld zseton van. Két húzást végzünk, visszatevés nélkül. Számítsa ki a következ® események valószín¶ségeit!
A kerületben a családok 36%-ának van kutyája, 30%-ának macskája. Azon családok közül, akiknek kutyájuk van, 22%-uknak van macskája is. (1-1 pont) (a) A családok hány százalékának van kutyája és macskája is? (b) A macskás családok közül véletlenszer¶en választunk egyet. Mennyi a valószín¶sége, hogy ennek a családnak van kutyája is?
A lakosság 17%-a lakik Budapesten, 20% megyei jogú városokban (ill megyeszékhelyen), 32% egyéb városokban, 31% községben. Az átlagot meghaladó számú baráttal rendelkez®k aránya településtípusonként eltér®. Budapesten 30%, megyeszékhelyeken ill. megyei jogú városban 25%, városokban 20%, községekben 10%. Számold ki az alábbi valószín¶ségeket! (A valós helyzetet némiképp egyszer¶sítve kapcsolatszegényekr®l és kapcsolatgazdagokról fogunk beszélni. Ide a végeredményeket írd le (tizedestörtben pl: 0, 123) A következ® oldalon vezesd le azokat, amik nem nyilvánvalóak. Nyilvánvalónak tekinthet® egy számítás, ha a feladat szövege tartalmazza a kért adatot, vagy ha 1-b®l kivonva valamelyik már meglév® eredményt kapjuk meg a megoldást. Ha így, 1-b®l kivonva kaptad az adott eredményt, annak rövid (rövid) levezetése erre az oldalra kerüljön! Pl: P(nem budapesti) = 1 − 0, 17 = 0, 83.
Egy községben az iskolába kerül® gyerekek 20%-a roma (minden évben). A községben egy iskola m¶ködik, 2 osztály indul. Az a osztály, és b osztály. Az igazgató állítása szerint a gyerekeket véletlenszer¶en sorolják be az egyes osztályokba, de egy szakért® az
Egy párt a legutóbbi választáson 24%-ot szerzett. A párt a választás után korrupciós botrányba keveredett. A botrány után egy 400 f®s véletlen mintán 21%-os támogatottságot mértek. Vajon ez statisztikai bizonyíték arra, hogy változott a párt támogatottsága? A feladat megoldása során készítsen ábrát! (a) Mi a nullhipotézis? (b) Mi az ellenhipotézis? (c) Mennyi a tesztstatisztika értéke? (d) Mekkora a számított szignikancia szint? (e) Ezek alapján (5%-os szignikancia szint mellett) elmondható, hogy csökkent a párt támogatottsága?
A Pew Research 2013 decemberében és 2014 januárjában felvett 2464 f®s mintája alapján Indiában a gazdasági helyzetet a megkérdezettek 62%-a jónak ítélte. 2012-ben ez az arány a populációban 60, 2% volt. 1. Bizonyíték mindez arra, hogy a 2013-as évben szignikánsan javult Indiában a gazdasági helyzet megítélése? 5%-os els®fajú hiba mellett döntsünk a kérdésben! 2. Legalább mekkora mintabeli arányt kellene kapnunk ahhoz, hogy 1%-os els®fajú hiba mellett el tudjuk utasítani a nullhipotézist? És 10%-os els®fajú hiba mellett? 3. Ha 5%-os els®fajú hiba mellett dolgozunk, akkor mekkora annak a valószín¶sége, hogy elutasítjuk a nullhipotézist, feltéve, hogy a valós arány a felvétel id®szakában 61% volt?
Egy 2017-ben végzett kutatás szerint a magyarok 12, 4%-a naponta beszélt a szüleivel. A kutatók a COVID alatt életbe lép® kijárási korlátozások hatására megváltozott társadalmi viszonyokra kíváncsiak, ezért egy 500 f®s telefonos kutatás végeznek. A megkérdezettek közül 80-an válaszolják azt, hogy az elmúlt id®szakban naponta beszélnek szüleikkel. 1. Változott a szül®k és gyermekek kapcsolattartási gyakorisága? Végezz hipotézisvizsgálatot 1%-os szignikancia szinten! 2. Mekkora annak a valószín¶sége, hogy elutasítjuk a nullhipotézist, feltéve, hogy a valós arány a felvétel id®szakában 13, 4% volt?
Egy kutató azt szerette volna vizsgálni, hogy van-e kapcsolat a házasságkötéskori életkor és a válás között. 784 f®s egyszer¶ véletlen mintát vettek a 40-60 éves, legalább 10 évvel ezel®tt házasodott népességb®l. A mintába került személyeket megkérdezte a házasodásuk és amennyiben elváltak a válásuk id®pontjáról. Az alábbi táblázat foglalja össze a tapasztalt adatokat:
Reformpedagógiai módszerrel dolgozó iskolákban érettségizettek felvételi eredményeit hasonlítjuk össze a hagyományos iskolában érettségiz®kével. Azt szeretnénk megvizsgálni, hogy vajon a reformpedagógiával tanító iskolák jobban teljesítenek-e. Az adataink véletlen mintákból származnak: A reform módszerrel tanuló diákok átlagos pontszáma a mintában 365, a minta korrigált szórása 24, a mintanagyság 30. A hagyományos módszerrel tanuló diákok átlagos pontszáma a mintában 362, a minta korrigált szórása 25, a mintanagyság 45.
Egy 2022-ban végzet 1044 f®s országos reprezentatív kutatás során többek között felmérték az egy f®re es® jövedelmet is (ezer forintban). Arra vagyunk kíváncsiak, vajon az adatok alapján a településtípus befolyásolja-e az egy f®re es® jövedelmet?
Magyarországon a járványt megel®z®en nagyon kevéssé volt elterjedt a távmunka, a járvány hatására ebben - átmenetileg - jelent®s változás következett be. A távmunka környezeti hatásai egyértelm¶en pozitívak, azonban a társadalmi hatásai már korántsem ilyen egyértelm¶ek. Egy kismintás pilot kutatásban a heti munkaid®t és hetente a gyermekekkel töltött id®t vizsgálták. Az alábbi adatokat kapták a kutatásban: Munkával töltött id® (óra/hét) 41 44 47 46 38 31 Gyermekkel töltött id® (óra/hét) 15 11 17 9 11 17 (a) Mennyi a munkával töltött id® korrigált szórása? (b) Mennyi a gyermekkel töltött id® korrigált szórása? (c) Mekkora a két változó kovarianciája? (d) Mekkora a két változó korrelációja?
Egy nagyobb vizsgálatban már 100 f®s véletlen mintát vettek. X - munkával töltött id® (óra/hét); Y - gyermekkel töltött id® (óra/hét). s ∗ x = 6, 1, s∗ y = 3, 5, covxy = −8, 6. Vajon ez az adat bizonyítja 1%-os els®fajú hiba szint mellett, hogy a munkával töltött id® negatívan befolyásolja a gyermekekkel töltött id®t? (a) Mennyi a korreláció? (b) Milyen próbát végzünk? (c) H0 és H1 számmal és szövegesen! (d) Tesztstatisztika és szabadsági fok? (e) Számított szignikancia szint hozzávet®leges értéke? (f) Döntés a hipotézisekr®l és szöveges magyarázat!
"Szabályos dobókockával háromszor dobunk; (1-1pont)a) P(1; 2; 3)=?  /mennyire valószínű, hogy először 1-est, másodiknak 2-est, harmadiknak 3-ast dobunk?/b) P(csupa páratlant dobunk)=?d) P(csupa négyest dobunk)=?e) P(egy hatost se dobunk)=?) P(dobunk hatost)=?  /legalább egyet/
"
Egymás után kétszer dobunk egy olyan cinkelt érmével, amelynél 0,7 a fejdobás valószínűsége. (1-1pont)a) Mennyire valószínű, hogy mindkétszer fejet kapunk?b) Mennyire valószínű, hogy mindkétszer írást kapunk?Katalóniában a legutóbbi függetlenségi népszavazáson a szavazásra jogosultak 40%-a ment el szavazni. A szavazáson megjelenők 90%-a függetlenség mellett szavazott, 10% a függetlenség ellen. (1-1pont)
Mekkora a teljes népességben azok aránya, akik elmentek szavazni és a függetlenségre szavaztak? (3pont)
Egy osztályban 45% a fiúk és 55% a lányok aránya. A fiúk 60%-a ügyes tornából, a lányok 65%-a ügyes tornából. Az ügyes tornászok aránya az osztályban 62,75%.Független egymástól a nem és a tornabeli ügyesség? igen/nem (aláhúzandó és indoklást is kérünk) (4pont)Számítsa ki a következő valószínűséget / arányt (gondoljon 1 fős véletlen mintára) (2 pont)
Egy városban az iskolába kerülő gyerekek 20%-a hátrányos helyzetű. A városban egy iskola működik, 2 osztály indul. Az „a” osztály matek tagozatos, a „b” osztály testnevelés tagozatos. Az igazgató állítása szerint a gyerekeket véletlenszerűen sorolják be az egyes osztályokba, de egy szakértő azt gyanítja, mégsem így van, hanem szegregáló a rendszer: a hátrányos helyzetű gyerekek kisebb eséllyel kerülnek az „a” osztályba. Idén a következőképpen alakultak azarányok: 1.a osztály: 30 tanulóból 4 hátrányos helyzetű, 26 nem hátrányos helyzetű
a, Mekkora a valószínűsége, hogy a 30 fős osztályba éppen 4 hátrányos helyzetű tanuló kerül be, ha véletlenszerűen sorsolnak? (3 pont)
b, Mekkora a valószínűsége, hogy a 30 fős osztályba éppen 3 hátrányos helyzetű tanuló kerül be, ha véletlenszerűen sorsolnak? (3 pont)
c, Mekkora a valószínűsége, hogy a 30 fős osztályba éppen 2 hátrányos helyzetű tanuló kerül be, ha véletlenszerűen sorsolnak? (3 pont)
, Mekkora a valószínűsége, hogy a 30 fős osztályba éppen 6 hátrányos helyzetű tanuló, ha véletlenszerűen sorsolnak? (3 pont)
2018 I. negyedévében KSH-adatok szerint Budapesten a munkavállalók 10% dolgozik távmunkában, míg vidéken 3 százalék. A munkavállalók 20%-a él Budapesten. (Az adatok a valósághoz közeliek, de kissé módosítottak). CSAK a fenti két mondat alapján töltse ki az adatokat. Ha van olyan információ, amit fejszámolással nem tud meghatározni, írja le ezt. Az alábbi kérdések a munkavállalókra vonatkoznak. (6 pont)
, Mennyi a távmunkában dolgozók aránya Magyarországon? (írja fel elsőként formalizálva!) (4 pont)
b, A távmunkában dolgozók közül kiválasztunk egy embert. Mekkora eséllyel lesz ő budapesti? (4 pont)
Egy számsorban kilenc 1-es és egy 12-es van. Számítsuk ki (papíron) a számsor átlagát és szórását. (4 pont)
Bergengóciában a Barna párt támogatottsága valahol 15-25% között lehet. Mintavételes vizsgálattal szeretnék ezt az arányt pontosabban megmérni: olyan pontosan, hogy a mintabeli százalékaránynak ne legyen 1%-nál nagyobb a standard hibája.Mekkora minta elég ehhez?
Ha a barnapártiak pontosan 15%-nyian lennének a populációban, akkor mekkora minta esetén lenne éppen 1% a barnapártiak mintabeli százalékarányának a standard hibája? (3 pont)
Ha a barnapártiak pontosan 25%-nyian lennének a populációban, akkor mekkora minta esetén lenne éppen 1% a barnapártiak mintabeli százalékarányának a standard hibája? (3 pont)
A rávezető kérdésekre rávezető kérdések:

a) ha a barnapártiak pontosan 15%-niyan lennének a populációban, akkor (minden sor 1+2 pont)

a1) egy n=100 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

a2) egy n=400 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

a3) egy n=900 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

a4) egy n=1600 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

b) ha a barnapártiak pontosan 25%-niyan lennének a populációban, akkor

b1) egy n=100 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

b2) egy n=400 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

b3) egy n=900 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira;

b4) egy n=1600 fős mintában a barnapártiak százalékaránya _____% körül lenne, attól +/- kb. ___%-nyira.

2.

Az CSÚCS bolthálózatban kapható egykilós kenyerek tömegét (mely változó) jelölje X; tegyük fel, hogy X normális eloszlású, μ=100 várható értékkel és σ=5 szórással. MINDKÉT FELADATHOZ KÉRÜNK RAJZOT! (3-3 pont)

a, A kenyerek (körülbelül) hány százaléka lesz 98 és 102 deka közötti tömegű?  (6 pont)

b, A kenyerek 90%-a ….. dkg alatti? Mit írhatunk …. helyére? (5 pont)
Egy párt a legutóbbi választáson 36,1%-ot szerzett. Pár hónappal később 900 fős véletlen mintán 38,2%-os támogatottságot mértek. Statisztikai bizonyíték ez 5%-os szignifikanciaszinten arra, nőtt a párt támogatottsága?

(1 pont) A statisztikai próba kiindulópontja:

(2 pont) Nullhipotézis …………………….. formalizálva

szövegesen:

(2 pont) Ellenhipotézis ………………………… formalizálva

szövegesen:

(3 pont) Tesztstatisztika számítása

(5 pont) Rajz

(1 pont) Tapasztalt szignifikancia-érték:…………………………………..

(3 pont) Ez minek a valószínűsége itt a konkrét példában?

(2 pont) Döntés

húzza alá a megfelelőt, majd a konkrét példára reflektálva szövegesen is fejtse ki a döntést:

megtartjuk a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük a nullhipotézist /

elvetjük az ellenhipotézist

VAGYIS:
1.feladat (összesen 25 pont) Egy párt tavaly a választáson 6,9%-ot ért el. Egy 1300 fős mintán most 7,5%-ra mérték a támogatottságukat. Statisztikai bizonyíték-e ez *-os szignifikanciaszinten arra, hogy növekedett a párt népszerűsége?

(1 pont) A statisztikai próba kiindulópontja:

(2 pont) Nullhipotézis ……………………..

formalizálva szövegesen:..........................

(2 pont) Ellenhipotézis …………………………

formalizálva szövegesen: ...............................

(1 pont) Ez egy egyoldali / kétoldali ellenhipotézis (aláhúzandó= írd le és húzd alá!!!!)

(3 pont) Tesztstatisztika számítása

(5 pont) Rajz

(2 pont) Tapasztalt szignifikancia-érték:…………………………………..

(2 pont) Ez minek a valószínűsége? (szöveges válasz)

(2 pont) Döntés (húzd alá, adj szöveges választ)

megtartjuk a nullhipotézist / elvetjük a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük a nullhipotézist

vagyis a konkrét esetben: ….

Milyen eredmény lenne bizonyító erejű 1%-os szignifikanciaszinten a növekedésre?

(2 pont) RAJZ

(3 pont) számítás
1. feladat (összesen 6 pont)

a, Mi az a vágópont, ami levágja?

az 5 szabadságfokú khi-négyzet eloszlás felső 5%-át? ……………

a 12 szabadságfokú khi-négyzset eloszlás felső 1%-át? ……………

a 20 szabadságfokú khi-négyzet eloszlás felső 95%-át? ……………..

b, Adjon intervallumbecslést: (összesen 7 pont)

1500 fős egyszerű véletlen mintán azt tapasztlatuk, hogy 64%-os arány támogatja a kalózpártot.

Határozza meg a következő értékeket

(1 pont) becslés standard hibája ……….

(2 pont) 95%-os konfidencia-intervallum

(2 pont) 99%-os konfidencia-intervallum

(2 pont) 99,9%-os konfidencia-intervallum

c, (3 pont) Ha 1000 tökéletesen szabályos dobókockát tesztelünk abból a szempontból, hogy nem dob-e a túl sok hatost, akkor 5%-os elsőfajú hibával dolgozva hány kockát fogunk kiszelektálni? Miért?

2. feladat (összesen 25 pont)

Egy gyártó nyereményjátékot hirdet. A nyereményjátékban azt ígérték, hogy a termékek 15%-a nyer. 600 darabos egyszerű véletlen mintán szeretné ellenőrizni a gyártó, hogy jól működik-e a gyártósor. Se túl sok, se túl kevés nyerőt nem szeretnének. A 600 darabos mintában 18% volt a nyerők aránya Statisztikai bizonyíték-e ez *-os szignifikanciaszinten arra, hogy rosszul működik a gyártósor?

(1 pont) A statisztikai próba kiindulópontja:

(2 pont) Nullhipotézis …………………….. formalizálva és szövegesen:

(2 pont) Ellenhipotézis ………………………… formalizálva és szövegesen:

(1 pont) Ez egy egyoldali / kétoldali ellenhipotézis (aláhúzandó)

(3 pont) Tesztstatisztika számítása

(5 pont) Rajz

(2 pont) Tapasztalt szignifikancia-érték:…………………………………..

(2 pont) Ez minek a valószínűsége?

(2 pont) Döntés

megtartjuk a nullhipotézist / elvetjük a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük az ellenhipotézist vagyis a konkrét esetben: ….
1. feladat (összesen 21 pont)

Bergengóciában öt párt tevékenykedik. Az alábbi táblázat a választáson elért eredményüket, valamint egy friss közvéleménykutatás eredményeit rögzíti. Változott-e a pártválasztás szerinti megoszlás? Végezzen illeszkedésvizsgálatot! 5%-os elsőfajú hiba mellett döntsön!

Választáson elért eredmény	Mintában tapasztalt megoszlás
A-párt	22,4%	64
B-párt	28,7%	95
C-párt	10,9%	24
D-párt	6,5%	28
E-párt	31,5%	89
100%	300
(1 pont) A statisztikai próba kiindulópontja:

(1 pont) Nullhipotézis

(1 pont) Ellenhipotézis

(1 pont) Szakmai hipotézis

(1 pont) Ez egy egyoldali / kétoldali statisztikai próba (aláhúzandó)

(5 pont) Tesztstatisztika számítás

(1 pont) szabadságfok …………………………..

(4 pont) Rajz

(2 pont) Tapasztalt szignifikancia-érték:…………………………………..

(2 pont) Ez minek a valószínűsége?

(2 pont) Döntés

megtartjuk a nullhipotézist / elvetjük a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük az ellenhipotézist

vagyis a konkrét esetben: ….

2. feladat (összesen 21 pont)

Egy kutató azt szerette volna vizsgálni, hogy van-e kapcsolat a kávéfogyasztás mennyisége és a depresszió tünetei között fiatal nők esetében. 3920 fős egyszerű véletlen mintát vettek a 20-30 közötti nők közül majd 10 év múlva újra felkeresték őket. Az alábbi táblázat foglalja össze a tapasztalt adatokat:

Depresszió tünetei jelentkeztek	Depresszió tünetei nem jelentkeztek	Összesen
Maximum hetente egyszer kávézik	150	453	603
Heti 2-6 csésze kávé	97	253	350
Napi 1 csésze kávé	400	801	1201
Napi 2 csésze kávé	280	532	812
Napi 3+ csésze kávé	350	604	954
Összesen	1277	2643	3920
Ezek alapján mit mondhatunk: független a két változó?

(1 pont) A statisztikai próba kiindulópontja:

(1 pont) Nullhipotézis

(1 pont) Ellenhipotézis

(1 pont) Szakmai hipotézis

(1 pont) Ez egy egyoldali / kétoldali statisztikai próba (aláhúzandó)

(5 pont) Tesztstatisztika számítása

(1 pont) szabadságfok …………………………..

(4 pont) Rajz

(2 pont) Tapasztalt szignifikancia-érték:…………………………………..

(2 pont) Ez minek a valószínűsége?

(2 pont) Döntés

megtartjuk a nullhipotézist / elvetjük a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük az ellenhipotézist

vagyis a konkrét esetben: ….
A kompetenciamérés országos átlaga Bergengóciában két éve 1597 pont volt. 40 fős egyszerű véletlen mintát vettünk, melyben a korrigált szórás 97 pont volt. Milyen mintabeli eredmény jelentene 1%-os elsőfajú hiba mellett bizonyítékot arra, hogy a populációban nőtt a mutató értéke?

(1 pont) Nullhipotézis

(4 pont) RAJZ

(2 pont) Határszámítás

2. feladat

A betegek térdfunkcióját egy KOOS nevet viselő skálával szokták mérni. Egy bizonyos műtét után a betegek térdfunkciója átlagosan 28-ról 31,5 pontra, vagyis 3,5 ponttal javult a 32 fős mintában (mindenkinél történt műtét előtti és műtét utáni mérés is.). A javulás korrigált szórása 9 pont.

Milyen próbát kell most végezni?

Egymintás Z / Egymintás T / Páros T / Függetlenmintás T / Khinégyzet illeszkedésvizságlatként / Khinégyzet összfüggésvizsgálatként?

Végezze el a megfelelő hipotézisvizsgálatot! (mindegyik lépést tüntesse fel!)
Reformpedagógiai módszerrel dolgozó iskolában érettségizettek eredményeit hasonlítjuk össze a hagyományos iskolában érettségizők átlagával. Adataink véletlen mintákból származnak:

reform átlag: 365 mintanagyság 30 korrigált szórás: 24



hagyományos átlag: 362 mintanagyság 45 korrigált szórás 25

hipotézisünk: a reformpedagógiával tanulók jobban teljesítenek



(1 pont) A statisztikai próba kiindulópontja:





(2 pont) Nullhipotézis



(2 pont) Ellenhipotézis





(1 pont) Ez egy egyoldali / kétoldali ellenhipotézis (aláhúzandó)



(3 pont) Tesztstatisztika számítása











(1 pont) Szabadságfok



(5 pont) Rajz















(2 pont) Tapasztalt szignifikancia-érték:…………………………………..

(2 pont) Ez minek a valószínűsége?









(2 pont) Döntés

megtartjuk a nullhipotézist / elvetjük a nullhipotézist / megtartjuk az ellenhipotézist / elvetjük az ellenh

ipotézist

vagyis a konkrét esetben: ….
Az alábbi kis elemszámú mintán számítsa ki az egyes statisztikai mutatók értékét és végezze el a hipotézisvizsgálatot is! (4 csoportból vett minta, az átlagokat szeretnénk összehasonlítani ANOVA-val.

A:	B:	C:	D:

Before applying the procedure to the full dataset, the matching score was tested on individual questions, including both a known homework copy and a question that was not copied from homework.

In [4]:
from thefuzz import fuzz

question = df['question'].iloc[151]

score = fuzz.partial_ratio(
    question.lower(),
    texts.lower()
)

print(score, question, len(question))

77 Mi a Z érték? 13

## Initial homework-copying criterion

Questions shorter than 50 characters were excluded because short questions produced less reliable matches during testing.

As a first criterion, questions of at least 50 characters were classified as homework copies when their fuzzy partial-ratio similarity with the reference document reached at least 90%.

In [5]:
def homework_flag(question):
    if not isinstance(question, str):
        return 0

    question = question.strip()
    length = len(question)

    if length < 50:
        return 0

    score = fuzz.partial_ratio(
        question.lower(),
        texts.lower()
    )

    if score >= 90:
        return 1
    else:
        return 0


df['homework'] = df['question'].apply(homework_flag)

print(df['homework'].value_counts())

print(
    df.loc[df['homework'] == 1, ['question', 'homework']]
)

homework
0    891
1     99
Name: count, dtype: int64
                                              question  homework
40   Tegyük fel, hogy a Bohócpárt támogatottsága az...         1
45   Mi az a vágópont, ami levágja?az 5 szabadságfo...         1
47   Ha 1000 tökéletesen szabályos dobókockát teszt...         1
50   Egy gyártó nyereményjátékot hirdet. A nyeremén...         1
65   Reformpedagógiai módszerrel dolgozó iskolában ...         1
..                                                 ...       ...
882  Az Egyesült Államok-beli Wind Energy Associati...         1
890  2. feladat: Az Egyesült Államok-beli Wind Ener...         1
901  mire kérdez rá, mit kell nézni? Fent a két nem...         1
931  Egy mobilszolgáltató 3 ügyfélköréből vett egys...         1
970  Szia! Az lenne a kérdésem, hogy ez milyen típu...         1

[99 rows x 2 columns]

At the 90% matching threshold, 99 questions were identified as homework copies. All identified questions were manually reviewed and confirmed as genuine matches. No false positive classifications were found.

The 50-character minimum was then tested separately by removing the length requirement while retaining the 90% similarity threshold.

In [6]:
def hw_new(question):
    if not isinstance(question, str):
        return 0

    question = question.strip()

    score = fuzz.partial_ratio(
        question.lower(),
        texts.lower()
    )

    if score >= 90:
        return 1
    else:
        return 0


df['hw1'] = df['question'].apply(hw_new)

print(df['hw1'].value_counts())

difference = df[
    (df['hw1'] == 1) &
    (df['homework'] == 0)
]

print(len(difference))

difference[['question', 'homework', 'hw1']]

hw1
0    876
1    114
Name: count, dtype: int64
15

                                 question  homework  hw1
80              Mi a szignifikanciaérték?         0    1
81                    mi a nullhipotézis?         0    1
152             Mi a szignifikanciaérték?         0    1
161                      mi a pontbecslés         0    1
207             mi a szignifikancia érték         0    1
218                                 Hogy          0    1
227                           S jelentése         0    1
228                     Szórás számítása          0    1
549  MIt fejez ki a szignifikancia érték?         0    1
692                        mit jelent a k         0    1
698                     KHÍ NÉGYZET PRÓBA         0    1
701                     KHÍ-NÉGYZET PRÓBA         0    1
753                                Miért?         0    1
768                      mi a pontbecslés         0    1
839                   mi a nullhipotézis?         0    1

The additional matches identified after removing the minimum character requirement included questions that could have arisen independently of the homework assignments as well as false positive classifications. The minimum character requirement was therefore retained.

In [7]:
df = df.drop(columns=['hw1'])

## Selection of the final matching threshold

The matching threshold was then relaxed while retaining the 50-character minimum. Thresholds of 85%, 80%, 75%, and 70% were considered.

The differences from the original 90% classification were examined manually to assess whether lowering the threshold improved the detection of genuine homework copies without introducing excessive false positives.

In [8]:
def hw_new2(question):
    if not isinstance(question, str):
        return 0

    question = question.strip()
    length = len(question)

    if length < 50:
        return 0

    score = fuzz.partial_ratio(
        question.lower(),
        texts.lower()
    )

    if score >= 75:
        return 1
    else:
        return 0


df['hw2'] = df['question'].apply(hw_new2)

print(df['hw2'].value_counts())

difference = df[
    (df['hw2'] == 1) &
    (df['homework'] == 0)
]

print(len(difference))

difference[['question', 'homework', 'hw2']]

hw2
0    865
1    125
Name: count, dtype: int64
26

                                              question  homework  hw2
27   a) Ha a barnapártiak pontosan 15%-nyian lennén...         0    1
31   Egy párt a legutóbbi választáson 36,1%-ot szer...         0    1
33   Egy párt a legutóbbi választáson 36,1%-ot szer...         0    1
39   (összesen 25 pont) Egy párt tavaly a választás...         0    1
46   Adjon intervallumbecslést:1500 fős egyszerű vé...         0    1
48   Egy gyártó nyereményjátékot hirdet. A nyeremén...         0    1
266  2. Mintavételes vizsgálattal akarják megmérni ...         0    1
311  Tegyük fel, hogy korábbi adatok szerint a magy...         0    1
335  És ez esetben mekkora lesz a tesztstatisztika ...         0    1
350  Hogyan interpretálható a regressziós b-együtth...         0    1
355  Ez alapján tudsz készíteni egy diagramot amely...         0    1
413  Mintavételes vizsgálattal akarják megmérni néh...         0    1
416   Mekkora valószínűséggel esik Z értéke a (2,∞)...         0    1
631  segitesz ebben legyszi:c) Milyen döntést hozun...         0    1
632  ennél a feladatnál lehet-e az a mullhipotézis,...         0    1
710  ,,Legalább mekkora mintabeli arányt kellene ka...         0    1
778  Khinégyzet próba illeszkedésvizsgálatként: Mi ...         0    1
824  Szia! Kérlek, segíts egy feladat megoldásában!...         0    1
832  Egy 2017-ben végzett kutatás szerint a magyaro...         0    1
838  Egy vállalkozás úgy döntött, hogy 100 dollár e...         0    1
844  8. Döntés (5% els®fajú hiba mellett): megtartj...         0    1
846  Elemezzük a koffeinfogyasztás (mg) és produkti...         0    1
861  mit jelent az egyoldali és kétoldali sttisztik...         0    1
883  Szia! Az lenne a kérdésem, hogy az alábbi fela...         0    1
884  És egy egyoldali vagy kétoldali statisztikai p...         0    1
923  A Cornell University egy kutatója azt vizsgált...         0    1

A 75% similarity threshold was selected as the final criterion. Lowering the threshold further resulted in an excessive number of false positive classifications.

All questions classified as homework copies under the final criterion were subsequently reviewed manually.

In [9]:
df = df.drop(columns=['homework', 'hw2'])

def homework_flag(question):
    if not isinstance(question, str):
        return 0

    question = question.strip()
    length = len(question)

    if length < 50:
        return 0

    score = fuzz.partial_ratio(
        question.lower(),
        texts.lower()
    )

    if score >= 75:
        return 1
    else:
        return 0


df['homework'] = df['question'].apply(homework_flag)

print(df['homework'].value_counts())

print(
    df.loc[df['homework'] == 1, ['question', 'homework']]
)

homework
0    865
1    125
Name: count, dtype: int64
                                              question  homework
27   a) Ha a barnapártiak pontosan 15%-nyian lennén...         1
31   Egy párt a legutóbbi választáson 36,1%-ot szer...         1
33   Egy párt a legutóbbi választáson 36,1%-ot szer...         1
39   (összesen 25 pont) Egy párt tavaly a választás...         1
40   Tegyük fel, hogy a Bohócpárt támogatottsága az...         1
..                                                 ...       ...
890  2. feladat: Az Egyesült Államok-beli Wind Ener...         1
901  mire kérdez rá, mit kell nézni? Fent a két nem...         1
923  A Cornell University egy kutatója azt vizsgált...         1
931  Egy mobilszolgáltató 3 ügyfélköréből vett egys...         1
970  Szia! Az lenne a kérdésem, hogy ez milyen típu...         1

[125 rows x 2 columns]

Five questions were manually reclassified from 1 to 0 after reviewing the algorithmic matches:

- Row 336, chat ID 26, question ID 44
- Row 351, chat ID 26, question ID 59
- Row 356, chat ID 27, question ID 2
- Row 779, chat ID 91, question ID 1
- Row 862, chat ID 110, question ID 1

After the manual corrections, 120 questions were classified as homework copies.

In [10]:
manual_corrections = [336, 351, 356, 779, 862]

df.loc[
    df['row_id'].isin(manual_corrections),
    'homework'
] = 0

## Homework copying and course relevance

The relationship between homework copying and course relevance was examined using a cross-tabulation.

In [11]:
print(
    pd.crosstab(
        df['homework'],
        df['relevance'],
        margins=True
    )
)

relevance    0    1  All
homework
0          128  742  870
1            0  120  120
All        128  862  990

The final classification identified 120 homework-copying questions and 128 irrelevant questions. The cross-tabulation showed that 742 questions were relevant course-related questions and were not classified as homework copies. No overlap was observed between irrelevant questions and homework-copying questions.

## User-level homework copying

A student-level measure was created to capture the proportion of a student's questions that were classified as homework copies.

In [12]:
hw_share = (
    df.groupby('id')['homework']
      .mean()
      .reset_index(name='hw_share')
)

df = df.merge(
    hw_share,
    on='id',
    how='left'
)

## Homework copying by reward period

Homework-copying rates were calculated separately for the rewarded and non-rewarded periods for each student.

In [13]:
df['hw_rw'] = df.loc[df['non_rewarded'] == 0, 'homework']
df['hw_nrw'] = df.loc[df['non_rewarded'] == 1, 'homework']

hw_period = (
    df.groupby('id')[['hw_rw', 'hw_nrw']]
      .mean()
      .reset_index()
      .rename(columns={
          'hw_rw': 'avg_hw_rw',
          'hw_nrw': 'avg_hw_nrw'
      })
)

df = df.merge(hw_period, on='id', how='left')

In [14]:
# Move row_id to the first column
cols = ['row_id'] + [col for col in df.columns if col != 'row_id']
df = df[cols]

In [15]:
df.to_excel('databases/chat_level_final.xlsx', index=False)